# Generated by Django 3.1.4 on 2023-08-10 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuzzlesSolved',
            new_name='Puzzles_Solved',
        ),
    ]
