# Generated by Django 4.2.3 on 2023-09-25 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_remove_puzzle_due_date_puzzle_term_puzzle_week'),
        ('users', '0004_submission_delete_puzzles_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='puzzle_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzles.puzzle'),
        ),
    ]
