# Generated by Django 4.2.3 on 2023-10-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('length', models.IntegerField(default=1)),
                ('current_week', models.IntegerField()),
            ],
        ),
    ]
