# Generated by Django 4.2.3 on 2023-10-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_alter_puzzle_term'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
