# Generated by Django 4.2.3 on 2023-07-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('due_date', models.DateField(null=True)),
            ],
        ),
    ]
