# Generated by Django 4.2.3 on 2023-08-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20230810_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
