# Generated by Django 4.2.3 on 2023-10-17 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('puzzles', '0005_rename_instruction_puzzle_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='due_date',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.term'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
