# Generated by Django 4.2.3 on 2023-10-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
        ('puzzles', '0006_remove_puzzle_due_date_puzzle_term_puzzle_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terms.term'),
        ),
    ]
