# Generated by Django 4.2.3 on 2023-11-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_auto_20231004_0143'),
        ('puzzles', '0008_puzzle_number'),
    ]

    operations = [
    ]
