# Generated by Django 4.2.3 on 2023-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0009_merge_0006_auto_20231004_0143_0008_puzzle_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
