# Generated by Django 4.2.3 on 2023-12-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_puzzle_explination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='explination',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='explanation',
            field=models.TextField(default='Insert Explanation'),
        ),
    ]
